export const proyectos = [
  {
    id: 1,
    nombre: "Sistema de Inventario",
    empresa: "TechCorp",
    duracion: "6 meses",
    dificultad: "alta",
    tipoProyecto: "back",
    imagen: "/views/proyectos/img/1.png",
  },
  {
    id: 2,
    nombre: "Portal de E-commerce",
    empresa: "Shopify",
    duracion: "8 meses",
    dificultad: "media",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/2.png",
  },
  {
    id: 3,
    nombre: "Aplicación de Mensajería",
    empresa: "CommsApp",
    duracion: "12 meses",
    dificultad: "alta",
    tipoProyecto: "fullStack",
    imagen: "/views/proyectos/img/3.png",
  },
  {
    id: 4,
    nombre: "Gestor de Tareas",
    empresa: "TaskMaster",
    duracion: "4 meses",
    dificultad: "baja",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/4.png",
  },
  {
    id: 5,
    nombre: "Sistema de Reservas",
    empresa: "BookingSys",
    duracion: "7 meses",
    dificultad: "media",
    tipoProyecto: "back",
    imagen: "/views/proyectos/img/5.png",
  },
  {
    id: 6,
    nombre: "Dashboard de Ventas",
    empresa: "SalesPro",
    duracion: "5 meses",
    dificultad: "alta",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/6.png",
  },
  {
    id: 7,
    nombre: "Plataforma de Aprendizaje",
    empresa: "EduTech",
    duracion: "10 meses",
    dificultad: "alta",
    tipoProyecto: "fullStack",
    imagen: "/views/proyectos/img/7.png",
  },
  {
    id: 8,
    nombre: "Control de Inventario",
    empresa: "TechCorp",
    duracion: "6 meses",
    dificultad: "media",
    tipoProyecto: "bases datos",
    imagen: "/views/proyectos/img/8.png",
  },
  {
    id: 9,
    nombre: "Gestión de Empleados",
    empresa: "HRSolutions",
    duracion: "4 meses",
    dificultad: "baja",
    tipoProyecto: "back",
    imagen: "/views/proyectos/img/9.png",
  },
  {
    id: 10,
    nombre: "Sistema de Facturación",
    empresa: "FinanceSoft",
    duracion: "6 meses",
    dificultad: "alta",
    tipoProyecto: "bases datos",
    imagen: "/views/proyectos/img/10.png",
  },
  {
    id: 11,
    nombre: "Aplicación de Recetas",
    empresa: "Foodies",
    duracion: "5 meses",
    dificultad: "media",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/11.png",
  },
  {
    id: 12,
    nombre: "Plataforma de Streaming",
    empresa: "StreamLive",
    duracion: "12 meses",
    dificultad: "alta",
    tipoProyecto: "fullStack",
    imagen: "/views/proyectos/img/12.png",
  },
  {
    id: 13,
    nombre: "Gestión de Proyectos",
    empresa: "PMTools",
    duracion: "8 meses",
    dificultad: "media",
    tipoProyecto: "back",
    imagen: "/views/proyectos/img/13.png",
  },
  {
    id: 14,
    nombre: "Sitio Web Corporativo",
    empresa: "BizSolutions",
    duracion: "3 meses",
    dificultad: "baja",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/14.png",
  },
  {
    id: 15,
    nombre: "Sistema de Contabilidad",
    empresa: "FinanceSoft",
    duracion: "9 meses",
    dificultad: "alta",
    tipoProyecto: "back",
    imagen: "/views/proyectos/img/15.png",
  },
  {
    id: 16,
    nombre: "Aplicación de Clima",
    empresa: "WeatherNow",
    duracion: "4 meses",
    dificultad: "baja",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/16.png",
  },
  {
    id: 17,
    nombre: "Gestión de Biblioteca",
    empresa: "LibrarySys",
    duracion: "5 meses",
    dificultad: "media",
    tipoProyecto: "bases datos",
    imagen: "/views/proyectos/img/17.png",
  },
  {
    id: 18,
    nombre: "E-commerce de Moda",
    empresa: "FashionStore",
    duracion: "8 meses",
    dificultad: "alta",
    tipoProyecto: "fullStack",
    imagen: "/views/proyectos/img/18.png",
  },
  {
    id: 19,
    nombre: "Aplicación de Fitness",
    empresa: "FitLife",
    duracion: "6 meses",
    dificultad: "media",
    tipoProyecto: "front",
    imagen: "/views/proyectos/img/19.png",
  },
  {
    id: 20,
    nombre: "Control de Gastos",
    empresa: "BudgetApp",
    duracion: "5 meses",
    dificultad: "baja",
    tipoProyecto: "back",
    imagen: "/views/proyectos/img/20.png",
  },
];
